### ISSUE TITLE
Atividade 17

### ISSUE THREAD

**Issue by B3nedito** [ProfRonan/primeiros-n-primos-B3nedito#2]
a = int(input("Digite um número:"))

b = 2

c =  30

while a > 01

if b == 2 or b == 3 or b 5 or b 7 or b = 11 or b 13 or b = 17 or b 19 or b= 23 or b == 29 :

          print(b)

          a  - =1

            b+ =1

       elif b < 30:
           
             b+=1
       else:

           break

while a  > 0:

if c % 2 == 0 or c % 3 == 0 or c % 5 ==0 or c % 7 ==0 or c % 9 ==0:

         3+3
        C+=1

else:

print(c)
      C+=1
      a-=1
if a == 0: 
 Break

**Comment by SeuRonao** [comment]
A atividade é para ser feita dando um commit. Eu já disse em sala várias vezes, e inclusive já respondi que assim não podia.
